# SPDX-FileCopyrightText: 2022 Brian Kubisiak <brian@kubisiak.com>
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "squashfile"
version = "0.0.0"
authors = ["Brian Kubisiak <brian@kubisiak.com>"]
edition = "2018"